"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyboardButtonCode = void 0;
var KeyboardButtonCode;
(function (KeyboardButtonCode) {
    KeyboardButtonCode[KeyboardButtonCode["Enter"] = 13] = "Enter";
    KeyboardButtonCode[KeyboardButtonCode["RShift"] = 16] = "RShift";
    KeyboardButtonCode[KeyboardButtonCode["Space"] = 32] = "Space";
    KeyboardButtonCode[KeyboardButtonCode["Num1"] = 49] = "Num1";
    KeyboardButtonCode[KeyboardButtonCode["Num2"] = 50] = "Num2";
    KeyboardButtonCode[KeyboardButtonCode["Num3"] = 51] = "Num3";
    KeyboardButtonCode[KeyboardButtonCode["Num4"] = 52] = "Num4";
    KeyboardButtonCode[KeyboardButtonCode["Left"] = 37] = "Left";
    KeyboardButtonCode[KeyboardButtonCode["Up"] = 38] = "Up";
    KeyboardButtonCode[KeyboardButtonCode["Right"] = 39] = "Right";
    KeyboardButtonCode[KeyboardButtonCode["Down"] = 40] = "Down";
    KeyboardButtonCode[KeyboardButtonCode["A"] = 65] = "A";
    KeyboardButtonCode[KeyboardButtonCode["B"] = 66] = "B";
    KeyboardButtonCode[KeyboardButtonCode["D"] = 68] = "D";
    KeyboardButtonCode[KeyboardButtonCode["E"] = 69] = "E";
    KeyboardButtonCode[KeyboardButtonCode["F"] = 70] = "F";
    KeyboardButtonCode[KeyboardButtonCode["G"] = 71] = "G";
    KeyboardButtonCode[KeyboardButtonCode["I"] = 73] = "I";
    KeyboardButtonCode[KeyboardButtonCode["K"] = 75] = "K";
    KeyboardButtonCode[KeyboardButtonCode["L"] = 76] = "L";
    KeyboardButtonCode[KeyboardButtonCode["O"] = 79] = "O";
    KeyboardButtonCode[KeyboardButtonCode["R"] = 82] = "R";
    KeyboardButtonCode[KeyboardButtonCode["S"] = 83] = "S";
    KeyboardButtonCode[KeyboardButtonCode["T"] = 84] = "T";
    KeyboardButtonCode[KeyboardButtonCode["W"] = 87] = "W";
    KeyboardButtonCode[KeyboardButtonCode["X"] = 88] = "X";
    KeyboardButtonCode[KeyboardButtonCode["Z"] = 90] = "Z";
})(KeyboardButtonCode = exports.KeyboardButtonCode || (exports.KeyboardButtonCode = {}));
