[features]
resolution = true
skip-lint = false

[programs.devnet]
tank_movement = "Aaxx2EcXQA5My5isrPw35FWPGUve4jaiW8u3ER9c9tRu"

[provider]
cluster = "https://rpc.magicblock.app/devnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "app/src/idl/"
